### ISSUE TITLE
Heavy quark FF switching

### ISSUE THREAD

**Issue by aaccardi** [JeffersonLab/JAMLIB#2]
(1) The JAM native grids do not have nodes at Q2 = mb^2 and mc^2, so FF(c) and FF(vb) will not properly go to zero when Q<mc,mb

(2) Probably related to teh previous, the JAMLIB.get_xF() fucntion returns non-zero values when Q<mc,mb.  For now I take care of this in my LHAPDF creation notebook, but I think it should be fixed at the JAMLIB level

**Comment by jethier** [comment]
This issue has been resolved and the current tables now properly treat the heavy quark thresholds.
